### ISSUE TITLE
Adruino Can Com

### ISSUE THREAD

**Issue by aceycv8** [Tbruno25/canopy#2]
Hi Tbruno25

First of all great design and thankyou for sharing with the community.

A question about which devices can be used?
Can we use an arduino with a canbus chip on it like you wrote up for canano and point to the arduino comm port? or do we have to use a specific device?

thank you

**Comment by Tbruno25** [comment]
@aceycv8 thank you for the kind words! 

Just about any CAN device should be able to work properly as long as it can be read by the python-can library.

In the case of Arduino, you will need to edit the `config` file  for use with [CAN over serial](https://python-can.readthedocs.io/en/master/interfaces/serial.html). Also ensure the messages are formatted properly per their examples.

**Comment by Tbruno25** [comment]
@aceycv8 I made a slight modification to the utility and added an example script for use with Arduino. 

Please re download/update `canopy.py`. The sketch to load onto your Arduino is in the `scripts` dir of this repo.

**Comment by zaasman** [comment]
I just got this setup working for myself, with an Arduino feeding can messages from my truck over serial to CanoPy. Works a treat, what a fantastic little tool this is, thank you @Tbruno25!

A small note that may be useful for someone: you'll have to additionally install the python serial package if you don't already have it:

`$ pip install pyserial`
