### ISSUE TITLE
Using candumps instead of live traffic from interface

### ISSUE THREAD

**Issue by Udoachim** [Tbruno25/canopy#3]
Would it be possible to adjust canopy to also allow for the visualization of recorded candumps instead of connecting to an interface? I have recorded several candumps and would like to analyze them using canopy for reverse engineering.

e.g. for candump message format
`(1620458408.814144) can3 0C000003#0150140000000000`
`(1620458408.814144) can3 0CFF0303#6400000000000000`
`(1620458408.814144) can0 069#9102460028284600`

**Comment by Tbruno25** [comment]
These logs can be visualized by setting the `config` to a virtual interface and redirecting the output to the same interface with canplayer. 

For example, if you have pre existing logs that were originally recorded using `can0` the command would look like --
`canplayer -I candump-messages.log vcan0=can0`

Thank you for the question -- I should add better documentation to address this as it's definitely a useful feature.
