### ISSUE TITLE
Python Error?

### ISSUE THREAD

**Issue by aceycv8** [Tbruno25/canopy#4]
Hi guys

After being side tracked i've come back to revisit this project.

I've build a laptop with ubutu on it and i've cloned the repository and run the install as per the instructions.

However when i run command: python canopy -i serial -c /dev/ttyACM0 -b 115200
i get the following error:

File "canopy.py", line 20
def __init__(self, buffer: defaultditct,, *args, **kwargs):
                                   ^
syntaxerror: invalid syntax

can anyone assist? 

thank you

**Comment by aceycv8** [comment]
i think i resolved it as i can get the app to run but i will do some can logging over the next few days.

a couple of issues on my part..
dont use python canopy as a command

new install of ubuntu i had to do the following:
sudo chmod a+rw /dev/ttyACM0
sudo apt install qtcreator

**Comment by Tbruno25** [comment]
glad you got it figured out! by explicitly stating `python` you likely were utilizing 2.7 which was causing errors. 

I'm going to close this but if you run into other issues feel free to re-open.
