### ISSUE TITLE
Logging How To?

### ISSUE THREAD

**Issue by aceycv8** [Tbruno25/canopy#5]
Hi Bruno

i'm getting back into the canbus hacking project again and trying to figure out this world :)

how is it possible to make a log file of the canbus entries from your canopy software?

i see the oscilloscope moving up and down and i use the volume on my stereo - how do i determine what the message packet are - as i see high and low but how do i know what the packet data is to tie this into my arduino project?

thank you

**Comment by Tbruno25** [comment]
What CanoPy does is take an existing data stream or log and help visualize it. It doesn't assist with acquiring the data itself.

If you're using a regular arduino you're going to need a CAN controller and transceiver to interact with the bus. I wrote [this article](https://tbruno25.medium.com/car-hacking-the-can-bus-tutorial-i-wish-i-had-783d7e0a2046) a few years ago that you may find useful, or you may want to use a more up to date one.

**Comment by aceycv8** [comment]
Awesome thanks for your help once again.

With your assistance with these sketches i've nearly completed my project of enabling bluetooth streaming to my vehicle with integrated steering wheel controls. appreciate your work - thank you
